project:
  type: website
  output-dir: docs
  
website:
  title: "Francisco Madrid-Gambin"
  description: "Biomedical Scientist, Data Scientist and Science Communicator working on multi-omics, health and psychedelic research."

  navbar:
    left:
      - text: About
        href: about.qmd
      - text: Scientific Communication
        href: science-communication.qmd
    right:
      - icon: github
        href: https://github.com/Francisco-madrid-gambin
      - icon: linkedin
        href: https://www.linkedin.com/in/francisco-madrid-gambin-phd-74489010a/
      - icon: youtube
        href: https://www.youtube.com/@Frankhasi
      - icon: tiktok
        href: https://www.tiktok.com/@frankhasi

format:
  html:
    page-layout: full
    theme:
      light: flatly
    css: styles.css
    toc: false
    smooth-scroll: true
