project:
  type: website
  output-dir: docs
  
website:
  title: "Francisco Madrid-Gambin"
  navbar:
    left:
      - text: About
        href: about.qmd
      - text: Projects
        href: projects.qmd
    right:
      - icon: github
        href: https://github.com/Francisco-madrid-gambin
      - icon: linkedin
        href: https://www.linkedin.com/in/francisco-m-74489010a/

format:
  html:
    page-layout: full
    theme:
      light: flatly
    css: styles.css
    toc: false
    smooth-scroll: true
